/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,jsx,ts,tsx}"],
  screens: {
    sm: "480px",
    md: "768px",
    lg: "976px",
    xl: "1440px",
  },
  theme: {
    colors: {
      blue: "#0f172a",
      purple: "#7e5bef",
      pink: "#ff49db",
      orange: "#ff7849",
      green: "#13cea2",
      yellow: "#ffc82c",
      "gray-dark": "#273444",
      gray: "#8492a6",
      "gray-light": "#d3dce6",
      darkpink: "#dc6aa8",
      lightblue: "#6cb4d9",
      dark: "#6cb4d9",
      white: "#ffffff",
      "primary-button": "#04adc0",
      "primary-color": "#d0d7df",
      button: "#687792",
      input: "#f3f7ff",
      "background-light": "#4553d8",
      "background-dark": "#0817b0",
      loginicon: "#0803c6",
    },
    extend: {},
  },
  plugins: [],
};